"""removed created at column from votes table

Revision ID: 5b77a6f424e9
Revises: bc6574379078
Create Date: 2026-02-18 21:33:19.221227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b77a6f424e9"
down_revision: Union[str, Sequence[str], None] = "bc6574379078"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DATETIME(),
                server_default=sa.text("(now())"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###
