"""Create tables

Revision ID: c5193b2f9ca2
Revises:
Create Date: 2025-12-02 15:27:25.596629

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c5193b2f9ca2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
