"""added address column in users table

Revision ID: feaff2d4e670
Revises: 1042aaa21c01
Create Date: 2025-08-11 18:47:33.888626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "feaff2d4e670"
down_revision: Union[str, Sequence[str], None] = "1042aaa21c01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("address", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "address")
    # ### end Alembic commands ###
